# Generated by Django 5.1 on 2024-08-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserInfo',
        ),
    ]
